name: FastAPI CI/CD

on:
  push:
    branches: 
      - main

jobs:

  CI:
    runs-on: ubuntu-latest
    steps:   
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install Python Virtual ENV
        run: pip install virtualenv

      - name: Cache Virtual ENV
        uses: actions/cache@v3
        id: cache-venv
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Activate Virtual ENV
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'

      - name: Run Tests
        run: |
          source venv/bin/activate
          python -m unittest discover -s tests -p "*.py"
      
       # Step 4: Zip all files in the ZANIA-ECOMMERCE folder
      - name: Zip all files
        run: |
          zip -r zania-ecommerce.zip ./*

      # Step 5: Upload zip file as artifact
      - name: Upload zip file artifact
        uses: actions/upload-artifact@v3
        with:
          name: zania-ecommerce
          path: zania-ecommerce.zip

  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      # Step 1: Download the artifact
      - name: Download zania-ecommerce zip artifact
        uses: actions/download-artifact@v3
        with:
          name: zania-ecommerce

      # Step 2: Install AWS CLI
      - name: Install AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Upload to S3
      - name: Upload to S3
        run: aws s3 cp zania-ecommerce.zip s3://ecommerce-deploy/zania-ecommerce.zip

      # Step 4: Deploy to Lambda
      - name: Deploy Lambda
        run: aws lambda update-function-code --function-name ecommerce-lambda --s3-bucket ecommerce-deploy --s3-key zania-ecommerce.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

          
